### ISSUE TITLE
tsify builds only root file with typescript 1.8

### ISSUE THREAD

**Issue by dlebedynskyi** [TypeStrong/tsify#110] opened 2016-02-03 18:50 UTC
Please refer to  for more details.
https://github.com/Microsoft/TypeScript/issues/6875

In short 
```
var bro = browserify('src/bootstrap.tsx', {
    cache: {}, packageCache: {},
    debug: !!debug
  })
.plugin(tsify, {
    "target": "es6", //!!
    "module": "commonjs",
    "sourceMap": true,
    "noImplicitAny": false,
    "jsx": "react", //!!
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true
    typescript: require('typescript')})
...
```
included only bootstrap in bundle. any relative imports are ignored.  node modules imports are fine.

**Comment by yangmillstheory** [comment] 2016-02-07 22:53
I'm seeing something similar. I have a simple test project:

`gulpfile.babel.js`:

```javascript
import gulp from 'gulp';
import browserify from 'browserify';
import vinylSource from 'vinyl-source-stream';
import vinylBuffer from 'vinyl-buffer';
import tsify from 'tsify';
import babelify from 'babelify';
import typescript from 'typescript';
import tsConfig from './tsconfig.json';


let bundleStream = function() {
  return browserify()
    .add([
      'index.ts'
    ])
    .plugin(tsify, {typescript})
    .transform(babelify.configure({extensions: ['.ts']}))
    .bundle()
    .pipe(vinylSource('bundle.js'))
    .pipe(vinylBuffer());
};

gulp.task('bundle', function() {
  return bundleStream()
    .pipe(gulp.dest('.'));
});
```

`tsify` + `1.8` emits:

```javascript
(function e(t,n,r){function s(o,u){if(!n[o]){if(!t[o]){var a=typeof require=="function"&&require;if(!u&&a)return a(o,!0);if(i)return i(o,!0);var f=new Error("Cannot find module '"+o+"'");throw f.code="MODULE_NOT_FOUND",f}var l=n[o]={exports:{}};t[o][0].call(l.exports,function(e){var n=t[o][1][e];return s(n?n:e)},l,l.exports,e,t,n,r)}return n[o].exports}var i=typeof require=="function"&&require;for(var o=0;o<r.length;o++)s(r[o]);return s})({1:[function(require,module,exports){
"use strict";

},{}],2:[function(require,module,exports){
"use strict";

var _foo = require("./foo");

var _foo2 = _interopRequireDefault(_foo);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

console.log("foo.foo1: " + _foo2.default.foo1);
console.log("foo.foo2(): " + _foo2.default.foo2());
console.log("THING: " + _foo.THING);
console.log("foo.coolThing: " + _foo2.default.coolThing);

},{"./foo":1}]},{},[2]);
```

In the browser:

```shell
Uncaught TypeError: _foo2.default.foo2 is not a function
```

`tsify` + `1.7.5` emits: 

```javascript
(function e(t,n,r){function s(o,u){if(!n[o]){if(!t[o]){var a=typeof require=="function"&&require;if(!u&&a)return a(o,!0);if(i)return i(o,!0);var f=new Error("Cannot find module '"+o+"'");throw f.code="MODULE_NOT_FOUND",f}var l=n[o]={exports:{}};t[o][0].call(l.exports,function(e){var n=t[o][1][e];return s(n?n:e)},l,l.exports,e,t,n,r)}return n[o].exports}var i=typeof require=="function"&&require;for(var o=0;o<r.length;o++)s(r[o]);return s})({1:[function(require,module,exports){
"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
var coolThing = exports.coolThing = "coolThing";

},{}],2:[function(require,module,exports){
"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = { bar: "bar" };

},{}],3:[function(require,module,exports){
"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});

var _bar = require("./bar");

var _bar2 = _interopRequireDefault(_bar);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

exports.default = { bar: _bar2.default };

},{"./bar":2}],4:[function(require,module,exports){
"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
var foo1 = "foo1";
exports.default = { foo1: foo1 };

},{}],5:[function(require,module,exports){
"use strict";

Object.defineProperty(exports, "__esModule", {
    value: true
});
exports.default = {
    foo2: function foo2() {
        console.log("foo2");
    }
};

},{}],6:[function(require,module,exports){
"use strict";

Object.defineProperty(exports, "__esModule", {
    value: true
});
exports.THING = undefined;

var _bar = require("./bar");

var _bar2 = _interopRequireDefault(_bar);

var _foo = require("./foo1");

var _foo2 = _interopRequireDefault(_foo);

var _foo3 = require("./foo2");

var _foo4 = _interopRequireDefault(_foo3);

var _bar3 = require("../bar");

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

exports.default = {
    foobar: function foobar() {
        return "foo" + _bar2.default.bar;
    },
    foo1: _foo2.default.foo1,
    foo2: _foo4.default.foo2,
    coolThing: _bar3.coolThing
};
var THING = exports.THING = "THING";

},{"../bar":1,"./bar":3,"./foo1":4,"./foo2":5}],7:[function(require,module,exports){
"use strict";

var _foo = require("./foo");

var _foo2 = _interopRequireDefault(_foo);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

console.log("foo.foo1: " + _foo2.default.foo1);
console.log("foo.foo2(): " + _foo2.default.foo2());
console.log("THING: " + _foo.THING);
console.log("foo.coolThing: " + _foo2.default.coolThing);

},{"./foo":6}]},{},[7]);
```

And in the browser, the bundle is fine:

```shell
bundle.js:96 foo.foo1: foo1
bundle.js:49 foo2
bundle.js:97 foo.foo2(): undefined
bundle.js:98 THING: THING
bundle.js:99 foo.coolThing: coolThing
```

**Comment by etse** [comment] 2016-02-19 06:57
I just want to add thar I have the same issue with TS 1.8

**Comment by pocesar** [comment] 2016-02-22 05:43
1.8 usage with the plugin is completely broken, plus it takes 30s+ seconds for outputting a 5kb (instead of the expected 255kb) file with gibberish like 

```js
(function e(t,n,r){function s(o,u){if(!n[o]){if(!t[o]){var a=typeof require=="function"&&require;if(!u&&a)return a(o,!0);if(i)return i(o,!0);var f=new Error("Cannot find module '"+o+"'");throw f.code="MODULE_NOT_FOUND",f}var l=n[o]={exports:{}};t[o][0].call(l.exports,function(e){var n=t[o][1][e];return s(n?n:e)},l,l.exports,e,t,n,r)}return n[o].exports}var i=typeof require=="function"&&require;for(var o=0;o<r.length;o++)s(r[o]);return s})({1:[function(require,module,exports){

},{}],2:[function(require,module,exports){
'use strict';
var bootstraper_1 = require('../shared/bootstraper');
require('./core/base');
bootstraper_1.boot('/admin.json');
},{"../shared/bootstraper":10,"./core/base":3}],3:[function(require,module,exports){
arguments[4][1][0].apply(exports,arguments)
},{"dup":1}],4:[function(require,module,exports){
arguments[4][1][0].apply(exports,arguments)
},{"dup":1}],5:[function(require,module,exports){
arguments[4][1][0].apply(exports,arguments)
},{"dup":1}],6:[function(require,module,exports){
arguments[4][1][0].apply(exports,arguments)
},{"dup":1}],7:[function(require,module,exports){
arguments[4][1][0].apply(exports,arguments)
},{"dup":1}],8:[function(require,module,exports){
arguments[4][1][0].apply(exports,arguments)
},{"dup":1}],9:[function(require,module,exports){
arguments[4][1][0].apply(exports,arguments)
},{"dup":1}],10:[function(require,module,exports){
```

**Comment by LPGhatguy** [comment] 2016-02-23 20:48
I've reached this issue too and it's blocking us upgrading to TypeScript 1.8. I'll take a look into it.

**Comment by vivainio** [comment] 2016-02-24 20:47
Watching as well, blocking my 1.8 migration

**Comment by joelday** [comment] 2016-02-29 01:36
There's something wrong with the module resolution where sometimes filenames are coming back as absolute paths in places they weren't before. Not really sure why.

I've got a fork that fixes it, but I haven't tested everything thoroughly yet, don't know if there are regressions or if there are issues with using earlier versions of TypeScript.

https://github.com/joelday/tsify

**Comment by yangmillstheory** [comment] 2016-02-29 02:22
@joelday I tried your fork in my test repo https://github.com/yangmillstheory/tsify-tsc-1.8.0-test; looks like it works with 1.8.0 and 1.7.5. Bundling code is [here](https://github.com/yangmillstheory/tsify-tsc-1.8.0-test/blob/master/gulpfile.babel.js#L16).

```shell
tsify-tsc-1.8.0-test (master * u= ?!) $ more package.json | grep tsify
    "tsify": "github:joelday/tsify",
```

First with 1.8.0:

```shell
tsify-tsc-1.8.0-test (master * u= ?!) $ tsc -v
Version 1.8.0
tsify-tsc-1.8.0-test (master * u= ?!) $ node_modules/.bin/gulp bundle
[18:13:52] Requiring external module babel-register
[18:13:53] Using gulpfile ~/code/private/tsify-tsc-1.8.0-test/gulpfile.babel.js
[18:13:53] Starting 'bundle'...
[18:13:54] Finished 'bundle' after 1.34 s
tsify-tsc-1.8.0-test (master * u= ?!) $ node server.js
Serving request for URL: /
```

No errors in the browser, and I get all the right import side effects.

Then with 1.7.5: 
```shell
tsify-tsc-1.8.0-test (master * u= ?!) $ sudo npm i --save-dev typescript@1.7.5
test@1.0.0 /Users/valvarez/code/private/tsify-tsc-1.8.0-test
├─┬ tsify@0.13.2 (git://github.com/joelday/tsify.git#964a82c7fdc2a0505abfcccec4ea1fc129b4bd28)
│ └── typescript@1.8.2
└── typescript@1.7.5
npm WARN test@1.0.0 No repository field.
tsify-tsc-1.8.0-test (master * u= ?!) $ node_modules/.bin/gulp bundle
[18:15:37] Requiring external module babel-register
[18:15:38] Using gulpfile ~/code/private/tsify-tsc-1.8.0-test/gulpfile.babel.js
[18:15:38] Starting 'bundle'...
[18:15:39] Finished 'bundle' after 1.36 s
tsify-tsc-1.8.0-test (master * u= ?!) $ node server.js
Serving request for URL: /
```

Same as before; no errors and I see the right import side effects. 

What happens when you run

```shell
$ npm test
$ npm test-main
```

in your fork?

**Comment by joelday** [comment] 2016-02-29 22:13
@yangmillstheory I hit "tsx not supported in this version of TypeScript: 1.8.2" at one point during ```npm test```. Can't look further into it at the moment.

**Comment by kuon** [comment] 2016-03-04 18:22
All relative modules, eg `import * as Foor from './foo'`import as empty with typescript 1.8

**Comment by zapu** [comment] 2016-03-07 00:11
Apparently the issue has been fixed in this fork: https://github.com/joelday/tsify/commit/642a9e12e17d92bfba0f4cc1a249f9ebb5a3934e 

any word on when it will be fixed in main repo? Thanks

**Comment by pocesar** [comment] 2016-03-07 23:06
vscode 0.10.10 is now shipping with typescript 1.8.7, this need to be implemented ASAP. I can't use string guards type ATM because of tsify

**Comment by LPGhatguy** [comment] 2016-03-08 00:59
@pocesar Seeing as the project maintainers have been missing for over a month on the issue, your best bet is to use the fork provided by @joelday.

**Comment by pocesar** [comment] 2016-03-08 01:08
@LPGhatguy oh well, alright

**Comment by kuon** [comment] 2016-03-08 01:08
@smrq you think you can get this one fixed? It's a major blocker for the 1.8 upgrade. If you are busy elsewhere, which is perfectly understandable, perhaps you could pick another maintainer to keep the project alive? tsify has become a major stone in typescript dev I think it deserves to stay alive.

**Comment by secondwtq** [comment] 2016-03-08 11:10
+1 for @joelday 's fix, it seems TypeScript is using absolute path [since this commit](https://github.com/Microsoft/TypeScript/commit/b8a3564d284fb2344dcedcc603fcc23cd5a0f1f6).

**Comment by smrq** [comment] 2016-03-08 18:20
My apologies for the radio silence.  Thanks so much to @joelday, merging his fix in ASAP.

**Comment by zapu** [comment] 2016-03-08 18:24
Woah, thanks! :+1:

**Comment by smrq** [comment] 2016-03-08 18:27
Published as 0.14.0.  :tada:  Again, thanks @joelday, I know a lot of people were waiting on this.

**Closed by smrq** 2016-03-08 18:27 UTC

**Comment by kuon** [comment] 2016-03-08 18:50
Thanks.

**Comment by joelday** [comment] 2016-03-09 01:48
@smrq just happy to help!

**Comment by dlebedynskyi** [comment] 2016-03-09 15:38
@joelday @smrq  thanks for fix guys

**Comment by LPGhatguy** [comment] 2016-03-09 17:39
Thank you!
